title: k8s_home_labs
author: socraticDev

description: develop for kubernetes on your local machine

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

avatar: "/assets/img/avatar-icon.jpg"
title-img: "/assets/img/banner.png"

github: "socraticDevBlog"
twitter: "SocraticDevBlog"
mastodon: "mastodon.social/@socdev"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  mastodon: true
  github: true


timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
